# Generated by Django 4.1 on 2022-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='income_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
