# Generated by Django 4.1 on 2022-10-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_income_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='title',
            new_name='shop_name',
        ),
    ]
