# Generated by Django 4.1 on 2022-10-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_title_client_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='tel',
            new_name='phone',
        ),
    ]
