# Generated by Django 4.1.1 on 2022-10-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_tel_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='amount',
        ),
    ]
